{"when":1789465267,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.052s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/14084)"}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.004s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.188s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789465269,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 2.042s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789465269,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789465269,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789465270,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[14147:python3.9]"}
{"when":1789465292,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1789465292,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789465293,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789465365,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465365,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.037s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465365,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 8ffe27f1-071f-3dd2-3f24-77ac57ca32ee. (parent/pid: 4112/15424)"}
{"when":1789465365,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.004s Holotree restoration failure, see above [with 9 workers on 10 CPUs]."}
{"when":1789465365,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"environment creation\" was FAILURE, reason: Could not get lock for holotree. Quiting.","comment":"rcc point of view"}
{"when":1789465392,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465392,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.045s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465392,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.003s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 4112/15619)"}
{"when":1789465392,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.005s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789465393,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.116s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789465393,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.290s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789465393,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789465393,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789465394,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[15621:python3.9]"}
{"when":1789465394,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789465394,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789465395,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789465405,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465405,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.032s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465405,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dfdabf80-2640-ab40-aba8-8dd7f6eb850a. (parent/pid: 4112/15725)"}
{"when":1789465405,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.004s Holotree restoration failure, see above [with 9 workers on 10 CPUs]."}
{"when":1789465405,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"environment creation\" was FAILURE, reason: Could not get lock for holotree. Quiting.","comment":"rcc point of view"}
{"when":1789465411,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465411,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.037s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465411,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 4112/15797)"}
{"when":1789465411,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.004s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789465412,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.125s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789465412,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.280s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789465412,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789465412,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789465413,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[15802:python3.9]"}
{"when":1789465413,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789465413,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789465414,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789466171,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.064s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/20160)"}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.124s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.319s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789466171,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789466171,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789466171,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20175:rcc]"}
{"when":1789466172,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 1 to 1 ... map[20175:python3.9]"}
{"when":1789466172,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789466172,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789466173,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789466184,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.040s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/20391)"}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.119s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.282s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789466184,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789466184,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789466185,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20403:python3.9]"}
{"when":1789466185,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789466185,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789466186,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789466614,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789466614,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.045s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789466614,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.003s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 4112/25296)"}
{"when":1789466614,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.004s Holotree blueprint is \"7535b7f5f6802b06\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789466614,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 03/15 v17.28.4 0.003s Fill hololib from RCC_REMOTE_ORIGIN skipped. RCC_REMOTE_ORIGIN was not defined."}
{"when":1789466614,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 04/15 v17.28.4 0.004s Cleanup holotree stage for fresh install."}
{"when":1789466614,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 05/15 v17.28.4 0.004s Build environment into holotree stage \"/Users/Shared/robocorp/ht/hcb88164_0cc3ca830dec7ft\"."}
{"when":1789466614,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 06/15 v17.28.4 0.004s Restore partial environment into holotree stage \"/Users/Shared/robocorp/ht/hcb88164_0cc3ca830dec7ft\"."}
{"when":1789466616,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 07/15 v17.28.4 1.965s Skipping micromamba phase, layer exists."}
{"when":1789466632,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 08/15 v17.28.4 15.471s Running pip install phase. (pip v23.0.1) [layer: 7535b7f5f6802b06]"}
{"when":1789466672,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 09/15 v17.28.4 39.828s Post install scripts phase skipped -- no scripts."}
{"when":1789466672,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 10/15 v17.28.4 0.019s Activate environment started phase."}
{"when":1789466674,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 11/15 v17.28.4 2.505s Pip check skipped."}
{"when":1789466674,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 12/15 v17.28.4 0.006s Update installation plan."}
{"when":1789466674,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 13/15 v17.28.4 0.017s Record holotree stage to hololib [with 9 workers on 10 CPUs]."}
{"when":1789466676,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 1.899s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789466678,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 1.937s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789466678,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789466678,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789466678,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[25977:rcc]"}
{"when":1789466679,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 1 to 1 ... map[25977:python3.9]"}
{"when":1789466681,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789466681,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789466682,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789466812,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789466812,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.051s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789466812,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.025s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/28006)"}
{"when":1789466812,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.004s Holotree blueprint is \"7535b7f5f6802b06\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789466812,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.128s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789466813,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.316s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789466813,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789466813,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789466813,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[28008:python3.9]"}
{"when":1789466814,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789466814,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789466815,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789467031,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789467031,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.044s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789467031,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/29736)"}
{"when":1789467031,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.005s Holotree blueprint is \"7535b7f5f6802b06\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789467031,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.117s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789467032,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.257s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789467032,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789467032,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789467032,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[29740:python3.9]"}
{"when":1789467033,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789467033,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789467034,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789645354,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789645354,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.072s Context: \"ankitlamsal\" \u003cankit@ankitlamsals-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.5.2; BuildVersion: 25F84]."}
{"when":1789645354,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 51e3ce73-4a50-6aa9-e449-06d98c2cfe9a. (parent/pid: 99489/453)"}
{"when":1789645354,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"617db99b12b81d0f\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789645354,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.216s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789645355,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.500s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789645355,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789645355,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789645355,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[461:python3.9]"}
{"when":1789645358,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1789645358,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789645359,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789645430,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789645430,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.084s Context: \"ankitlamsal\" \u003cankit@ankitlamsals-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.5.2; BuildVersion: 25F84]."}
{"when":1789645430,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment 51e3ce73-4a50-6aa9-e449-06d98c2cfe9a. (parent/pid: 99489/1285)"}
{"when":1789645430,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.004s Holotree blueprint is \"617db99b12b81d0f\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789645430,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.171s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789645431,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.484s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789645431,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789645431,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789645432,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[1289:python3.9]"}
{"when":1789645441,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789645441,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789645442,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789645599,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789645599,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.080s Context: \"ankitlamsal\" \u003cankit@ankitlamsals-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.5.2; BuildVersion: 25F84]."}
{"when":1789645599,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment 51e3ce73-4a50-6aa9-e449-06d98c2cfe9a. (parent/pid: 99489/1898)"}
{"when":1789645599,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.005s Holotree blueprint is \"617db99b12b81d0f\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789645600,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.175s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789645600,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.504s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789645600,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789645600,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789645601,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[1906:python3.9]"}
{"when":1789645603,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[1906:python3.9 1917:osascript]"}
{"when":1789645604,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[1906:python3.9]"}
{"when":1789645637,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1789645637,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789645638,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789645646,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789645646,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.047s Context: \"ankitlamsal\" \u003cankit@ankitlamsals-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.5.2; BuildVersion: 25F84]."}
{"when":1789645646,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 51e3ce73-4a50-6aa9-e449-06d98c2cfe9a. (parent/pid: 99489/2275)"}
{"when":1789645646,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.005s Holotree blueprint is \"617db99b12b81d0f\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789645646,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.176s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789645647,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.466s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789645647,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789645647,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789645648,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[2278:python3.9]"}
{"when":1789645659,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789645659,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789645660,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
