{"when":1789465267,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.052s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/14084)"}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.004s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789465267,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.188s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789465269,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 2.042s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789465269,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789465269,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789465270,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[14147:python3.9]"}
{"when":1789465292,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1789465292,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789465293,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789465365,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465365,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.037s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465365,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 8ffe27f1-071f-3dd2-3f24-77ac57ca32ee. (parent/pid: 4112/15424)"}
{"when":1789465365,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.004s Holotree restoration failure, see above [with 9 workers on 10 CPUs]."}
{"when":1789465365,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"environment creation\" was FAILURE, reason: Could not get lock for holotree. Quiting.","comment":"rcc point of view"}
{"when":1789465392,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465392,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.045s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465392,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.003s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 4112/15619)"}
{"when":1789465392,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.005s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789465393,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.116s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789465393,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.290s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789465393,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789465393,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789465394,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[15621:python3.9]"}
{"when":1789465394,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789465394,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789465395,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789465405,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465405,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.032s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465405,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dfdabf80-2640-ab40-aba8-8dd7f6eb850a. (parent/pid: 4112/15725)"}
{"when":1789465405,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.004s Holotree restoration failure, see above [with 9 workers on 10 CPUs]."}
{"when":1789465405,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"environment creation\" was FAILURE, reason: Could not get lock for holotree. Quiting.","comment":"rcc point of view"}
{"when":1789465411,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789465411,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.037s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789465411,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 4112/15797)"}
{"when":1789465411,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.004s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789465412,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.125s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789465412,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.280s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789465412,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789465412,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789465413,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[15802:python3.9]"}
{"when":1789465413,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789465413,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789465414,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789466171,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.064s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/20160)"}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.124s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789466171,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.319s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789466171,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789466171,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789466171,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20175:rcc]"}
{"when":1789466172,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 1 to 1 ... map[20175:python3.9]"}
{"when":1789466172,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789466172,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789466173,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
{"when":1789466184,"controller":"rcc.user","event":"start task","detail":"name= from=robot.yaml","comment":"at task environment setup"}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.040s Context: \"Ujjal Shrestha\" \u003cujjalshrestha@Ujjals-MacBook-Air.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 26.6.2; BuildVersion: 25G83]."}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment dd50733b-7fe4-42a2-2cd0-ecc22dc0dda0. (parent/pid: 11692/20391)"}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"e24d196af63b0408\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.119s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1789466184,"controller":"rcc.user","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.282s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1789466184,"controller":"rcc.user","event":"start","detail":"robot","comment":"started"}
{"when":1789466184,"controller":"rcc.user","event":"run","detail":"robot","comment":"task run"}
{"when":1789466185,"controller":"rcc.user","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20403:python3.9]"}
{"when":1789466185,"controller":"rcc.user","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"user\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1789466185,"controller":"rcc.user","event":"processes","detail":"final","comment":"count: 0"}
{"when":1789466186,"controller":"rcc.user","event":"stop","detail":"robot","comment":"done"}
